baseURL = "https://udchen.tw/"
languageCode = "zh-TW"
title = "UD隨筆"
theme = "hyde"
disqusShortname = "udchenme"
enableemoji = true
hasCJKLanguage = true
# googleAnalytics = "G-NJ1YCLGFGV"
[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"
[Menus]
  main = [
      #{Name = "Twitter", URL = "https://twitter.com/udchen19/"},
      #{Name = "![Github](https://joshuapenalba.files.wordpress.com/2014/12/github-icon.png?w=30)", URL = "https://github.com/udchen19/"},
      {Name = "Posts", URL = "/posts"}
  ]
[params]
  themeColor = "theme-base-ud"
  layoutReverse = true
  description = "Thoughts. Notes. Anything whatsoever."
  mainSections = ['posts', 'blog']
[markup.goldmark.extensions]
  strikethrough = true
[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true
